### ISSUE TITLE
In small screen navbar is overlapped by home text

### ISSUE THREAD

**Issue by akshitjain2004** [akshitjain2004/Knots-MERN#1]

**Comment by leetebbs** [comment]
Hi,

Is this the issue you need resolving?

![knott](https://github.com/akshitjain2004/Knots-MERN/assets/6608795/011eaf9b-1f65-4423-af97-78566e42668a)

**Comment by akshitjain2004** [comment]
Hey @leetebbs,

Yes I need help to solve this issue, should I assign this issue to you ?

**Comment by leetebbs** [comment]
Hi 
yes please

I have made a pr

**Comment by akshitjain2004** [comment]
Merged. Thanks!!. Good work.

**Comment by leetebbs** [comment]
Great stuff.
Thanks
