### ISSUE TITLE
Create About Us Page 

### ISSUE THREAD

**Issue by akshitjain2004** [akshitjain2004/Knots-MERN#14]
Create a new About Us page, add a photo, or maybe a moving animation if you want to. Give  a paragraph of lorem ipsum

**Comment by drewduong** [comment]
I'd like to take this on! Can you allow me to contribute

**Comment by akshitjain2004** [comment]
@drewduong Yes, you can work on this !!

**Comment by akshitjain2004** [comment]
@drewduong Are you working on it ?
