### ISSUE TITLE
Enhance Vendor Page

### ISSUE THREAD

**Issue by akshitjain2004** [akshitjain2004/Knots-MERN#17]
Need help in enhancing vendor page. Folder name - Service.

**Comment by leetebbs** [comment]
Hi @akshitjain2004 
check out :
https://knots-mern.vercel.app/service
If you like it assign this to me and i'll do a pr

**Comment by akshitjain2004** [comment]
@leetebbs hey man! , it's looking good, but when you go on next page it's getting messy. I mean the colors. Can you please solve that, also can you make it responsive if it's possible and if you're free.
