### ISSUE TITLE
Need help in updating status when user  login and log out

### ISSUE THREAD

**Issue by akshitjain2004** [akshitjain2004/Knots-MERN#18]
I added Firebase authentication for this project. I want to update when the user logs in and logs out in the navbar and also we have to do routing (when the login is pressed after auth it should redirect to the homepage and show that the user is logged in)

**Comment by akshitjain2004** [comment]
@leetebbs can you help man? just tell me I'll do it

**Comment by leetebbs** [comment]
Hi Bud @akshitjain2004 
I can take a look tomorrow.

**Comment by akshitjain2004** [comment]
@leetebbs Thanks man! Appreciate ya !

**Comment by leetebbs** [comment]
@akshitjain2004 dm me on x so we can chat about the issue above
https://twitter.com/LTebbs2

**Comment by akshitjain2004** [comment]
@leetebbs followed you.  
https://x.com/hellcaster2004
