### ISSUE TITLE
Create Contact Us page

### ISSUE THREAD

**Issue by akshitjain2004** [akshitjain2004/Knots-MERN#2]
Need help in creating a contact us page

**Comment by QuangHuy1902** [comment]
Can you assign it for me?

**Comment by akshitjain2004** [comment]
Yes, try to make it responsive. All the best

**Comment by akshitjain2004** [comment]
@QuangHuy1902 Assigned this issue to you 👍🏻

**Comment by QuangHuy1902** [comment]
I have completed the issue. You can check it.

**Comment by QuangHuy1902** [comment]
TranQuangHuy11 is my other account.

**Comment by akshitjain2004** [comment]
@QuangHuy1902 I can't see the PR. Can you please check once?

**Comment by akshitjain2004** [comment]
@QuangHuy1902 Also send the screenshot of what you have made.

**Comment by QuangHuy1902** [comment]
![image](https://github.com/akshitjain2004/Knots-MERN/assets/146641219/d84ca80c-103f-40cf-ba40-4801af6f1cbc)

**Comment by QuangHuy1902** [comment]
![image](https://github.com/akshitjain2004/Knots-MERN/assets/146641219/8ff6595d-6302-4e8e-b1ee-f1bb11f51e80)
you can check here.

**Comment by akshitjain2004** [comment]
You have to make a pull request so I can accept it.

**Comment by QuangHuy1902** [comment]
Can you accept to merge my solution. I have been submit it.

**Comment by akshitjain2004** [comment]
@QuangHuy1902 Pr accepted. Thank you

**Comment by QuangHuy1902** [comment]
@akshitjain2004 you're welcome...!!!
