### ISSUE TITLE
Text is not visible . Need improvement in css

### ISSUE THREAD

**Issue by akshitjain2004** [akshitjain2004/Knots-MERN#20]
![image](https://github.com/akshitjain2004/Knots-MERN/assets/94056853/b3361623-a80c-4c1a-b2ff-28f5b3f91ce1)
Please try to make it responsive

**Comment by IrfanSalim** [comment]
hey, I would like to take this up

**Comment by akshitjain2004** [comment]
@IrfanSalim Assigned you!
