### ISSUE TITLE
Contact page is overlapped by footer

### ISSUE THREAD

**Issue by akshitjain2004** [akshitjain2004/Knots-MERN#5]
I used routers to link the pages but the contact page is getting overlapped by the footer.
![image](https://github.com/akshitjain2004/Knots-MERN/assets/94056853/8f0c4c2a-cb83-47fa-9888-56d6624ed545)

**Comment by leetebbs** [comment]
Hi @akshitjain2004  can you assign this to me?

**Comment by akshitjain2004** [comment]
Hey @leetebbs,  Yes
