### ISSUE TITLE
Enhance About  section 

### ISSUE THREAD

**Issue by sanika404** [akshitjain2004/Knots-MERN#6]
Need help in arranging the div's evenly and  please make them responsive. Also you have complete flexibility to recreate the about according to you. About us contains how our website works . 

![image](https://github.com/akshitjain2004/Knots-MERN/assets/134488939/9da46ed2-22f0-4bb9-9a46-d7ff8c859896)

**Comment by akshitjain2004** [comment]
@Achal-00 Amazing work. Merged PR.
